name: Build Warmup_deagle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Plugin
        # 使用 Release 模式編譯
        run: dotnet build --configuration Release --no-restore

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Warmup_deagle_Package
          # 這裡對應你 .csproj 裡的 OutputPath，但在 Linux 系統需使用正斜線 /
          # 它會抓取該資料夾下所有的檔案（包含 .dll 和 config.cfg）
          path: bin/Release/addons/counterstrikesharp/plugins/Warmup_deagle/
          if-no-files-found: error
